apiVersion: apps/v1
kind: Deployment
metadata:
  name: herbsfest
spec:
  template:
    spec:
      initContainers:
        - name: migrate
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: herbsfest-postgres-app
                  key: uri
      containers:
        - name: web
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: herbsfest-postgres-app
                  key: uri
