apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rundt
resources:
- ../../app
- ../../cnpg
- ingress.yaml
- middleware.yaml
- sealedsecret-basic-auth.yaml
patches:
- path: database-secret.yaml
- path: postgres.yaml
images:
- digest: sha256:19206ccad69e436354ee49a6d1ac1f4e062cfdce22a2960a10236a21183b42a7
  name: ko://github.com/tjrasche/HerbsfestOS/cmd/web
  newName: artifacts.r-und-t.app/herbsfest
