apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rundt
resources:
- ../../app
- ../../cnpg
- ingress.yaml
- middleware.yaml
- sealedsecret-basic-auth.yaml
- sealedsecret-auth-session.yaml
patches:
- path: database-secret.yaml
- path: postgres.yaml
- path: auth.yaml
images:
- digest: sha256:1998b10bbec14254d328abaa47459e1096ee9963e3eea59d2d9a1ea4bc4d7406
  name: ko://github.com/tjrasche/HerbsfestOS/cmd/web
  newName: artifacts.r-und-t.app/herbsfest
configMapGenerator:
- behavior: merge
  literals:
  - AUTH_MODE=oidc
  - ZITADEL_ISSUER=https://auth.r-und-t.app
  - APP_BASE_URL=https://herbstfest.r-und-t.app
  - ZITADEL_CLIENT_ID=394051797699788961
  - ZITADEL_PROJECT_ID=394051632024780961
  name: herbsfest-config
