---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: herbsfest-auth
  namespace: rundt
spec:
  encryptedData:
    AUTH_SESSION_KEY: AgAJGs7+32lrWrDCjLPf6XandGh5I47sHRttYHCKEa7O770ODmGHUZ0m773Akok+fOjy1MMgIOvCIOqSv/b2gElPMX4RlsGfQKLM8wnhDpWDwHMl/A0487J0gwSqvMQ+lUKWGSf78rPiBC2za/jNhBQ9kV55U2vXHvtGsMktI7jdGL0t7ysom5U6zJ49co+Yw5yCurTPQF9XnTkYKgA3mH8L2c945DCtFxyjcbIuAB4aTy4/A+jAP04zzc8xic6Opf7kLCu/zY+LZT6QSXfAq0eKIvjHA69g0ltT1b94UQAXbvN+ZBiCdN1QNBqo10P+lBAz99ENFbd3IH/KXCJN2H8PZTgcdxa3hfidLjRCxIBwGkKZ8ri3YEAwenMZuHt9STC2N0BopviRXHcbTkhK20Il7DKieWGYQhnMjb3ZfM7r4GEp8RLG9AQowmv0P4+O7hUzeau2wmRUI5RwayGibKOUs++CC6gvBDVFxOUxGpjStKOmEu22SdC4+AxgdG6LaYKGIOksupJj4DnGPZvcRpSZIKxXLhLHLjzsREajUJccu9IgUqKYu+CpBKUMmAOh2msQtSXGOgpPVk5l55Wt3bFrsVPqjCOyRql+z662nLOGg9TNHKH8K2ZGB0wX+XNIQV+L9J0IO4Mcw53ux7lY+WhjOJvrLpiA6MQ+PhbR45QdywJ9S6HYqt1OX0nthRp4BYyteJGKCgbNjIQgTmJfFDgX0RfXM51GKqRtBXlceGs1VKGzR3qSGe3EzBn9XA==
  template:
    metadata:
      name: herbsfest-auth
      namespace: rundt
    type: Opaque
