---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: herbsfest-basic-auth
  namespace: rundt
spec:
  encryptedData:
    users: AgBgRLVN0D+SxW+4fIw5ctRCEqcN8ICR6diQuzUUdxghK9rKkmcZ+0WcqC8oH3nPW7U3Bvf223dv+GwSdfEIb+UOMw8pDKzK0Ufco/sweDAEIVZ9dL+iKOXHR+10DMK33xFLlU7BlhR5xfC7BeWoaH55dQMlU/zhxnxTJBb9fXB34mEp1dRmZ33eFVaAQrnSJKgKmIVMbsKlodXN8Jxe65y+7RRHSK0QBazjDw0I+638Jov2EfSz1ljNwgNAcbI3/yFzjmfQ/BN96UsoqrKT7c6w2n4u6eHRTf4xEegphLBQRKjPPimJlJed2MkVmOG9t2qJ+HHBaFqCg0vwOyHabYsT6WeKFljtQ/ktAE0+EfrYLqboUzQAvVd5wlMrvPRHwx5g3YruPPIqM8b+88n1SuGh7jf7r68GNbn9aWg17HLklJL0SuKkbuSf/YnO7R2JAlQfCAT1CojimYr7nRnSYJIxoFK2pK0JG5Y6hReNodwtejZL0dJCElA5W3Owdv/nNCIihQA5o42G/DUQoMWkmgPq1U9kf2P9x43Y5A2B3cc5VQMKGZGypcbuTTqFBIJZxVo5EddJX1COyyjWJrke/cyHoCaTmQ8qVnzMznK5okP8IOQluBa7pUhf7bk4dy3T2y5UTi2w+ZX1nVYjYqbhqZO/Ue0z46w4+c9fdiJMHqad14HvLZXwYQ2uX7l665fuYfnsd37kV35dt/1KlvwfDlZlJmkv+CGs72jYk4HA6m3MkgTpb6mZZK3rj+TECBCXt+rEQ+V4pTXJHSFxTA6wbAjkUno=
  template:
    metadata:
      name: herbsfest-basic-auth
      namespace: rundt
